version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '3001:3001'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/ocrdb?schema=public

      OPENAI_API_KEY: sua-api-key-aqui
      JWT_SECRET: sua-chave-secreta
    volumes:
      - ./backend:/app
      - ./backend:/src/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: sua-chave-secreta
      BACKEND_URL: http://localhost:3001
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

    volumes:
      - ./frontend:/app
      - ./frontend:/src/node_modules

volumes:
  postgres_data:
